stages:
  - build
  - deploy

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run release
    - chmod +x ./app/make-nupkg.sh
    - ./app/make-nupkg.sh

  artifacts:
    paths:
      - release-builds/*.exe
      - release-builds/*.deb
      - release-builds/*.AppImage
      - release-builds/choco/openflexure-ev.nuspec
      - release-builds/choco/tools/chocolateyInstall.ps1

deploy:
  stage: deploy
  image: patrickhuber/choco-linux
  dependencies:
    - build
  script:
    - ls -R ./release-builds/
    - choco pack --allow-unofficial --outputdirectory "./release-builds/choco" "./release-builds/choco/openflexure-ev.nuspec"
  artifacts:
    paths:
      - release-builds/choco/*.nupkg