stages:
  - build
  - deploy

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run release
  artifacts:
    paths:
      - release-builds/*.exe
      - release-builds/*.deb
      - release-builds/*.AppImage

deploy:
  stage: deploy
  tags:
    - windows
  script:
    - .\app\make-nupkg.ps1
  artifacts:
    paths:
      - release-builds/*.nupkg