image: electronuserland/builder:wine

build:
  script:
    - npm install
    - npm run release
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - release-builds/*.exe
      - release-builds/*.deb
      - release-builds/*.AppImage
