stages:
  - build
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

build:
  stage: build
  image: electronuserland/builder:wine
  retry: 2
  script:
    - npm install
    - npm run release
    - tar -czvf "./release-builds/openflexure-ev-web.tar.gz" -C "./dist" .
    - chmod +x ./app/make-nupkg.sh
    - ./app/make-nupkg.sh
  artifacts:
    paths:
      - release-builds/*.exe
      - release-builds/*.deb
      - release-builds/*.AppImage
      - release-builds/*.tar.gz
      - release-builds/choco/openflexure-ev.nuspec
      - release-builds/choco/tools/chocolateyInstall.ps1
  only:
    - tags
    - web

deploy:
  stage: deploy
  image: patrickhuber/choco-linux
  dependencies:
    - build
  script:
    - cd ./release-builds/choco
    - ls -R
    - choco pack
    - choco apikey --key $CHOCO_API_KEY --source https://push.chocolatey.org/
    - choco push --source https://push.chocolatey.org/
  artifacts:
    paths:
      - release-builds/choco/*.nupkg
  only:
    - tags
