stages:
  - build
  - deploy

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run release
    - chmod +x ./app/make-nupkg.sh
    - ./app/make-nupkg.sh
  artifacts:
    paths:
      - release-builds/*.exe
      - release-builds/*.deb
      - release-builds/*.AppImage
      - release-builds/choco/openflexure-ev.nuspec
      - release-builds/choco/tools/chocolateyInstall.ps1
  only:
    - tags

deploy:
  stage: deploy
  image: patrickhuber/choco-linux
  dependencies:
    - build
  script:
    - cd ./release-builds/choco
    - ls -R
    - choco pack
    - choco apikey --key $CHOCO_API_KEY --source https://push.chocolatey.org/
    - choco push --source https://push.chocolatey.org/
  artifacts:
    paths:
      - release-builds/choco/*.nupkg
  only:
    - tags
