directories:
  output: release-builds
  buildResources: app/resources
appId: org.openflexure.ev
artifactName: ${name}-${os}-${arch}.${ext}
asar: true
files:
  - filter:
      - '**/*'
      - '!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}'
      - '!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}'
      - '!**/node_modules/*.d.ts'
      - '!**/node_modules/.bin'
      - '!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}'
      - '!.editorconfig'
      - '!**/._*'
      - '!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}'
      - '!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}'
      - '!**/{appveyor.yml,.travis.yml,circle.yml}'
      - '!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}'
      - '!**/.env.*'
      - '!**/{.idea,.vscode}${/*}'
      - '!**/app/installers${/*}'
      - '!**/hooks${/*}'
      - '!**/platforms${/*}'
      - '!**/release-builds${/*}'
      - '!src${/*}'
mac:
  icon: app/icons/mac/icon.icns
  category: public.app-category.utilities
dmg:
  contents:
    - x: 110
      y: 150
    - x: 240
      y: 150
      type: link
      path: /Applications
linux:
  target:
    - AppImage
    - target: deb
      arch:
        - x64
        - armv7l
  icon: app/icons/png/1024x1024.png
deb:
  category: Science
win:
  target:
    - NSIS
  icon: app/icons/win/icon.ico
electronVersion: 4.1.5
