extends: app/builder-config-base.yaml
electronVersion: 4.1.5
win:
  target:
    - NSIS
  icon: app/icons/win/icon.ico
linux:
  target:
    - target: deb
      arch:
        - x64
    - target: appImage
      arch:
        - x64
  icon: app/icons/png/
  category: Science
mac:
  icon: app/icons/mac/icon.icns
  category: public.app-category.utilities
dmg:
  contents:
    - x: 110
      y: 150
    - x: 240
      y: 150
      type: link
      path: /Applications
