extends: app/builder-config-base.yaml
linux:
  target:
    - target: deb
      arch:
        - armv7l
  icon: app/icons/png/1024x1024.png
  category: Science
deb:
  category: Science
  fpm: ['--architecture', 'armhf']
electronVersion: 3.0.13
