extends: app/builder-config-base.yaml
linux:
  target:
    - AppImage
    - target: deb
      arch:
        - x64
        - armv7l
  icon: app/icons/png/1024x1024.png
deb:
  category: Science
electronVersion: 4.1.5
