extends: app/builder-config-base.yaml
linux:
  target:
    - AppImage
    - target: deb
      arch:
        - armv7l
  icon: app/icons/png/1024x1024.png
  category: Science
deb:
  category: Science
electronVersion: 3.0.13
