extends: app/builder-config-base.yaml
linux:
  target:
    - AppImage
    - target: deb
      arch:
        - x64
  icon: app/icons/png/
  category: Science
deb:
  category: Science
electronVersion: 4.1.5
